var map;var markers=[];var address;var view={};var largeInfoWindow;view.initMap=function(){map=new google.maps.Map(document.getElementById('map'),{center:{lat:28.5272181,lng:77.0688976},zoom:8,mapTypeControl:!1})}
view.initialize=function(locations){largeInfoWindow=new google.maps.InfoWindow({maxWidth:250});var pinColor;var pinImage;for(var i=0;i<locations.length;i++){var position=locations[i].position;var title=locations[i].name;var id=locations[i].id;switch(locations[i].type){case 'school':pinColor="59c605";break;case 'college':pinColor="05c6bd";break;case 'hospital':pinColor="c60505";break;case 'mall':pinColor="0905c6";break;case 'multiplex':pinColor="db36c2";break;case 'tourist':pinColor="ead219";break}
pinImage=new google.maps.MarkerImage("https://chart.apis.google.com/chart?chst=d_map_pin_letter&chld=%E2%80%A2|"+pinColor);var marker=new google.maps.Marker({position:position,title:title,animation:google.maps.Animation.DROP,id:id,icon:pinImage});markers.push(marker);marker.addListener('click',(function(c){return function(){view.populateInfoWindow(this,largeInfoWindow,locations[c])}})(i))};view.showlistings()};view.showlistings=function(){var bounds=new google.maps.LatLngBounds();for(var i=0;i<markers.length;i++){markers[i].setMap(map);bounds.extend(markers[i].position)}
map.fitBounds(bounds)};view.hidelistings=function(){for(var i=0;i<markers.length;i++){for(var k=0;k<hideMarkers.length;k++){if(i==hideMarkers[k])
markers[i].setMap(null)}}};view.getMarker=function(location){for(i=0;i<markers.length;i++){if(markers[i].id==location.id)
return markers[i]}}
view.getInfoWindow=function(){return largeInfoWindow}
view.populateInfoWindow=function(marker,infoWindow,location){markers.forEach(function(bouncemarker){bouncemarker.setAnimation(null)});marker.setAnimation(google.maps.Animation.BOUNCE);if(infoWindow.marker!=marker){infoWindow.marker=marker;infoWindow.setContent('');var article=view.wiki(location);infoWindow.setContent('<div><h1>'+marker.title+'</h1></div><hr>'+'<div class= "description"></div>')}
infoWindow.open(map,marker);infoWindow.addListener('closeclick',function(){infoWindow.marker=null;marker.setAnimation(null)})}
view.wiki=function(location){var article;var city='New Delhi';var name=location.name;var wikiurl='https://en.wikipedia.org/w/api.php?action=opensearch&search='+name+'&format=json&callback=wikiCallback';var wikiRequestTimeout=setTimeout(function(){article="Failed to Load wikipedia articles";$('.description').append(article)},8000);$.ajax({url:wikiurl,dataType:"jsonp",success:function(response){article=response[2];$('.description').append(article);clearTimeout(wikiRequestTimeout)}})}